/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [ProductKey]
      ,[ProductAlternateKey]
     -- ,[ProductSubcategoryKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode]
      ,[EnglishProductName] AS Product,
	  ps.EnglishProductSubcategoryName AS [Sub Category], -- Joined in from Sub Category Table
	  pc.EnglishProductCategoryName AS [Product Category], -- Joined in from Category Table
      --,[SpanishProductName]
      --,[FrenchProductName]
      [StandardCost]
      --,[FinishedGoodsFlag]
      ,[Color]
      ,[SafetyStockLevel]
      ,[ReorderPoint]
      ,[ListPrice]
      ,[Size]
      --,[SizeRange]
      --,[Weight]
      --,[DaysToManufacture]
     ,[ProductLine]
      ,[DealerPrice]
      --,[Class]
      --,[Style]
      ,[ModelName]
      --,[LargePhoto]
      ,[EnglishDescription]
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
     -- ,[GermanDescription]
     -- ,[JapaneseDescription]
      --,[TurkishDescription]
     -- ,[StartDate]
     -- ,[EndDate]
     -- ,[Status]
  FROM [AdventureWorksDW2019].[dbo].[DimProduct]
    LEFT JOIN AdventureWorksDW2019.dbo.DimProductSubcategory AS ps ON ps.ProductSubcategoryKey = ps.ProductSubcategoryKey 
    LEFT JOIN AdventureWorksDW2019.dbo.DimProductCategory AS pc ON ps.ProductCategoryKey = pc.ProductCategoryKey 